name: Market Scanner Cron

on:
  schedule:
    - cron: '*/15 3-9 * * 1-5'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Market Scan
        env:
          TELEGRAM_BOT_TOKEN: 8209156550:AAEmxEg-bWapX_7kk4bdwXk0lj-1meISdJA
          TELEGRAM_CHAT_ID: 951733992
        run: python scanner.py
